// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqINrNvoiPNvfBcOoLLN70kPPu-WcruFY',
    appId: '1:142307320311:web:7dc56522d0032d4f18cef2',
    messagingSenderId: '142307320311',
    projectId: 'mobile-app-e2c1f',
    authDomain: 'mobile-app-e2c1f.firebaseapp.com',
    storageBucket: 'mobile-app-e2c1f.firebasestorage.app',
    measurementId: 'G-0149S7Y0YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-m0ddse3QeaDrEbwEEr_jYz6SevSgrG8',
    appId: '1:142307320311:android:e9205fd4108dd55018cef2',
    messagingSenderId: '142307320311',
    projectId: 'mobile-app-e2c1f',
    storageBucket: 'mobile-app-e2c1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4yJc5-ONJNAZ3jxqOm5dTZredaSJ7kxw',
    appId: '1:142307320311:ios:449618a9f847a19718cef2',
    messagingSenderId: '142307320311',
    projectId: 'mobile-app-e2c1f',
    storageBucket: 'mobile-app-e2c1f.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4yJc5-ONJNAZ3jxqOm5dTZredaSJ7kxw',
    appId: '1:142307320311:ios:449618a9f847a19718cef2',
    messagingSenderId: '142307320311',
    projectId: 'mobile-app-e2c1f',
    storageBucket: 'mobile-app-e2c1f.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqINrNvoiPNvfBcOoLLN70kPPu-WcruFY',
    appId: '1:142307320311:web:99c4f2aff2b7ffef18cef2',
    messagingSenderId: '142307320311',
    projectId: 'mobile-app-e2c1f',
    authDomain: 'mobile-app-e2c1f.firebaseapp.com',
    storageBucket: 'mobile-app-e2c1f.firebasestorage.app',
    measurementId: 'G-4D6MMDXH8C',
  );
}
